#!/bin/sh

set -e

lb config noauto \
	--bootappend-live "boot=live components hostname=discreete username=somebody quiet splash" \
	--distribution jessie \
	--binary-images iso-hybrid \
	--bootloader syslinux \
	--checksums sha256 \
	--debian-installer false \
	--debian-installer-gui false \
	--debootstrap-options "--include=apt-transport-https,ca-certificates,openssl" \
	--linux-flavours amd64-unsigned \
	--linux-packages linux-image-4.7.0-dsctl1 \
	--iso-volume Discreete-Linux_2016.01 \
	--iso-publisher "Discreete Linux Team" \
	--firmware-chroot true \
	"${@}"
