#!/bin/sh

## live-config(7) - System Configuration Components
## Copyright (C) 2006-2014 Daniel Baumann <mail@daniel-baumann.ch>
##
## This program comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.


#set -e

Cmdline ()
{
        # Reading kernel command line
        for _PARAMETER in ${LIVE_CONFIG_CMDLINE}
        do
                case "${_PARAMETER}" in
                        live-config.username=*|username=*)
                                LIVE_USERNAME="${_PARAMETER#*username=}"
                                ;;
                esac
        done
}

Init ()
{
        # Checking if package is installed
        if [ ! -e /var/lib/dpkg/info/policykit-1.list ] || \
           [ -e /var/lib/live/config/policykit ]
        then
                exit 0
        fi

        echo -n " policykit"
}
Config ()
{
        # Grant administrative PolicyKit pivilieges to default user

        # Configure PolicyKit in live session
        mkdir -p /etc/PolicyKit

cat > /etc/PolicyKit/PolicyKit.conf << EOF
<?xml version="1.0" encoding="UTF-8"?> <!-- -*- XML -*- -->

<!DOCTYPE pkconfig PUBLIC "-//freedesktop//DTD PolicyKit Configuration 1.0//EN"
"http://hal.freedesktop.org/releases/PolicyKit/1.0/config.dtd">

<!-- See the manual page PolicyKit.conf(5) for file format -->

<config version="0.1">
        <match user="root">
                <return result="yes"/>
        </match>
EOF

cat >> /etc/PolicyKit/PolicyKit.conf << EOF
        <define_admin_auth group="sudo"/>
</config>
EOF

        # Creating state file
        touch /var/lib/live/config/policykit
}

Cmdline
Init
Config

